import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './_styles/globals.scss'

import AuthProvider from '@/common/utils/auth-provider'
import { Header } from '@/components'
import { Footer } from '@/components/ui/footer'
import StoreProvider from '@/app/store-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <StoreProvider>
          <AuthProvider>
            <Header />
            <main>{children}</main>
            <Footer />
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  )
}
